### ISSUE TITLE
Uncaught ErrorException: Class 'Tightenco\Collect\Support\Debug\Dumper' not found

### ISSUE THREAD

**Issue by ZigaStrgar** [tightenco/collect#126]
In my global composer directory where I have my laravel valet installed, I'm getting this error. Probably it is related to this: http://prntscr.com/krlymp

And here is the full dump of the error:

`PHP Fatal error:  Uncaught ErrorException: Class 'Tightenco\Collect\Support\Debug\Dumper' not found in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php:18
Stack trace:
#0 [internal function]: {closure}(2, 'Class 'Tightenc...', '/Users/zigastrg...', 18, Array)
#1 /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php(18): class_alias('Tightenco\\Colle...', 'Illuminate\\Supp...')
#2 /Users/zigastrgar/.composer/vendor/composer/autoload_real.php(66): require('/Users/zigastrg...')
#3 /Users/zigastrgar/.composer/vendor/composer/autoload_real.php(56): composerRequire59860c76f3932111d8d7b49da118e358('caf31cc6ec7cf22...', '/Users/zigastrg...')
#4 /Users/zigastrgar/.composer/vendor/autoload.php(7): ComposerAutoloaderInit59860c76f3932111d8d7b49da118e358::getLoader()
#5 /Users/zigastrgar/.composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer(60): require_once('/Users/zigastrg...')
#6 {main}
  thrown in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18

Fatal error: Uncaught ErrorException: Class 'Tightenco\Collect\Support\Debug\Dumper' not found in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php:18
Stack trace:
#0 [internal function]: {closure}(2, 'Class 'Tightenc...', '/Users/zigastrg...', 18, Array)
#1 /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php(18): class_alias('Tightenco\\Colle...', 'Illuminate\\Supp...')
#2 /Users/zigastrgar/.composer/vendor/composer/autoload_real.php(66): require('/Users/zigastrg...')
#3 /Users/zigastrgar/.composer/vendor/composer/autoload_real.php(56): composerRequire59860c76f3932111d8d7b49da118e358('caf31cc6ec7cf22...', '/Users/zigastrg...')
#4 /Users/zigastrgar/.composer/vendor/autoload.php(7): ComposerAutoloaderInit59860c76f3932111d8d7b49da118e358::getLoader()
#5 /Users/zigastrgar/.composer/vendor/friendsofphp/php-cs-fixer/php-cs-fixer(60): require_once('/Users/zigastrg...')
#6 {main}
  thrown in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18`

**Comment by Najki** [comment]
That's the second time when my tests started failing after updating this library and again, it's the `alias.php` file. The last time was in [february](https://github.com/tightenco/collect/issues/86). I think that some tests for `alias.php` file should be added at this point.

**Comment by ImLiam** [comment]
For what it's worth, this package follows the [Laravel versioning scheme](https://laravel.com/docs/5.6/releases#versioning-scheme) which is NOT the semantic versioning you're used to with Composer. Instead of locking to a minor version like `^5.6`, prefer to require a specific version like `5.6.*`.

Looks like the 5.7 branch is still currently a WIP.

**Comment by Najki** [comment]
Thanks buy when reporting an issue last time in february, I was using a `5.5.*` rule and it still meant that it updated from 5.5.32 to a bugged 5.5.33 so this time I'm not taking any chances and locking it on a fixed `5.6.38`.

**Comment by mattstauffer** [comment]
@najki curious: did your tests actually fail? Could you show me what they were doing that caused it to fail?

**Comment by Najki** [comment]
A few tests actually failed but I'm not authorized to show any code. The stacktrace looked very similar to the one provided by @ZigaStrgar but there was phpunit instead of php-cs-fixer at the end. I guess that any test of code using collect would fail, cause PHPUnit will load alias.php through Composer's `vendor/autoload.php` and `alias.php` tries to define aliases for classes which were deleted in 5.7.1 - `Dumper` and `HtmlDumper`.

**Comment by ZigaStrgar** [comment]
Same thing happens when I use any of valet commands. The only difference is that it outputs a warning instead of an error.

```
PHP Warning:  Class 'Tightenco\Collect\Support\Debug\Dumper' not found in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18

Warning: Class 'Tightenco\Collect\Support\Debug\Dumper' not found in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18
PHP Warning:  Class 'Tightenco\Collect\Support\Debug\HtmlDumper' not found in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18

Warning: Class 'Tightenco\Collect\Support\Debug\HtmlDumper' not found in /Users/zigastrgar/.composer/vendor/tightenco/collect/src/Collect/Support/alias.php on line 18
Restarting php...
Restarting nginx...
Valet services have been restarted.
```

**Comment by mattstauffer** [comment]
@ZigaStrgar Thanks!

For anyone who comes across this: Maintaining a llbrary that has its own internal logic but which also has to perfectly reflect the release schedule of another framework is not easy. If any of you feel passionate about adding more tests that would cover these circumstances I'd love for you to do so, as it's clearly something you care a lot about and we welcome open source pull requests from the community. Thanks!

**Comment by Najki** [comment]
> Maintaining a llbrary that has its own internal logic but which also has to perfectly reflect the release schedule of another framework is not easy.

Just sayin', but... people chose to use this library over Laravel's collection for a reason and I doubt that anybody would be upset if it stopped matching Laravel's release dates/versions perfectly while introducing more stability instead.

**Comment by mattstauffer** [comment]
The problem is, the actual core code of Collect perfectly mimics Laravel’s. This is necessary for hot swap compatibility and it’s also the only way for us to have a not insane mapping between Laravel’s changes and ours.
